### ISSUE TITLE
How to use npm/yarn link with a local copy of tonal

### ISSUE THREAD

**Issue by devboell** [danigb/tonal#41] opened 2017-09-29 08:01 UTC
When I use `yarn link` in the root of the tonal package, it links `tonal-core`. I can import `tonal-core` in my own project, and it works, but is this the expected behaviour?

If I cd to `packages/tonal` and link there, it links tonal, but when I `import * as tonal from 'tonal'` in my project I get:

```
dev/experiments/tonal-exp/node_modules/tonal/node_modules/tonal-array/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { midi, name } from "tonal-note";
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/tonal/build/transpiled.js:5:13)
      at Object.<anonymous> (src/tests/index.test.js:3:13)
```

This also happens when I use `const tonal = require('tonal')`

**Comment by danigb** [comment] 2017-09-29 08:09
Yes. The tonal facade package is under `packages/tonal` so, to link with yarn you should:

```
cd packages/tonal
yarn link
```

Anyway, if you are in a ES6 enviroment (because you are using rollup or webpack) you can use the tonal package distribution directly:

```
yarn add tonal
```

and:

```
import tonal from "tonal"
```

**Comment by devboell** [comment] 2017-09-29 08:23
sure, for normal development I use `yarn add tonal`. The `yarn link` is handy if I would experiment with the tonal code itself. So right now I get an error if I link the tonal 'facade'.

**Comment by danigb** [comment] 2017-09-29 08:25
What error?... I used `yarn link` with tonal "facade" with no errors...

**Comment by devboell** [comment] 2017-09-29 08:30
Well, sorry if I haven't been clear.
The error doesn't appear when I use `yarn link` in packages/tonal.
It happens when I make a separate project and want to use the tonal link there. Like:

```
cd my-project
yarn link tonal
```

then in `my-project/index.js`, using `import * as tonal from 'tonal'` results in the error I reported above.

**Comment by danigb** [comment] 2017-09-29 08:35
Well,  ES6 modules it's a headache for me too. The thing is: browser nor node doesn't understand "import" statements, so if you are using it you MUST transpile the code before running it. Two common scenarios: 

- create-react-app: it uses webpack under the hood to transpile the sources from ES6 modules to CommonJS modules before sending the code to the browser. You can use "import" with no modifications and it will work.
- a simple node or browser app: you must use a transpiler (rollup or webpack are the most common alternatives) to compile the source and then run that compiled source

So, if you are not transpiling, use require. 

Hope it helps

**Comment by devboell** [comment] 2017-09-29 08:52
I'm not sure you're getting my point, I am always transpiling my own sources. However (with Webpack at least), babel will not transpile the sources that I import from node_modules, they already have to be transpiled.
  So with the normal scenario of `yarn add tonal`, I can now import the transpiled tonal sources in my local project (because of the fix in the previous issue).
 But with the link scenario, for some reason, it still imports the untranspiled tonal code.

**Comment by danigb** [comment] 2017-09-29 09:05
Yes, I didn't get your point. Now it's more clear. I've made some changes in the source code that may solve your issue (and published a new 1.0.0-pre2 version with the changes). Let me know if it works now.

**Comment by danigb** [comment] 2017-09-29 09:29
In fact, I'm having a similar issue trying to integrate tonal with react... It takes the index.js file instead of the transpiled.js file. It uses "main" and "module" tags from package.json... I don't know why this is happening, so ideas are welcomed...

**Comment by devboell** [comment] 2017-09-29 09:46
I'll try to help out, but it should be independent of react. Are you having trouble with the `yarn add` scenario, or the 'yarn link` scenario? And where is you react app?

**Comment by danigb** [comment] 2017-09-29 09:53
Yes, it should be independent of react. I tried both scenarios (yarn add and yarn link) and the problem is that webpack is using the not transpiled version and it fails when minimizing the code. I don't know why it uses "index.js" instead of "build/transpiled.js"

**Comment by devboell** [comment] 2017-09-29 10:55
ok, I made four test apps on my machine:
- add scenario, node/jest app
- link scenario, node/jest app
- add scenario, webpack/react app
- link scenario, webpack/react app

All four work!

So, if you like I can push the four apps to my github, so you can have a look and compare with your app.
And/Or, I can take a look at your react app and see if I find something wrong with the webpack config. Or clone your app on my machine and see if I can get it working here.

**Comment by danigb** [comment] 2017-09-29 11:20
@devboell thanks a lot! Finally I've managed to solve it by publishing an es6 transpiled version (so now, for each module, there is a es5.js file with transpiled code and CommonJS modules, and a es6.js file with transpiled code and es6 modules). It seems that webpack in `create-react-app` don't transpile "module" sources.

I'm writing a demo app to showcase the possibilities of tonal. You can see it in action here: https://danigb.github.io/tonal-app/ and the source code here: https://github.com/danigb/tonal-app

Currently is a work in progress, but suggestions or help is welcomed.

I'm going to close this issue, but feel free to reopen if needed.

Thanks!!

**Closed by danigb** 2017-09-29 11:20 UTC

**Comment by devboell** [comment] 2017-09-29 11:53
ok, glad it's all working
