### ISSUE TITLE
Getting double flattened notes in scale.notes

### ISSUE THREAD

**Issue by walmik** [danigb/tonal#69] opened 2018-10-18 16:25 UTC
Hello @danigb 

First up this is a brilliant library and it s one of the main dependencies of a module called [Scribbletune](url) that I ve put together in order to provide a bunch of music generation functionality.

I wanted to know if there is a way to avoid getting double flattened notes? For instance, `scale.notes('Db4 minor')` will return  `[ 'Db4', 'Eb4', 'Fb4', 'Gb4', 'Ab4', 'Bbb4', 'Cb5' ]`. 
Here is there some way to not get `A4` instead of `Bbb4`? 

Similarly if I do `scale.notes('d#4 major')` I get `[ 'D#4', 'E#4', 'F##4', 'G#4', 'A#4', 'B#4', 'C##5' ]`
Here is there some way to not return double sharps? So that instead of `F##4`, I d get `G4` instead.

Many thanks in advance!

**Comment by danigb** [comment] 2018-10-18 16:29
Yes, there's a reason: to preserve intervals. It used to be a`enharmonic` module that allow to "simplify" a note (get the same pitch with simpler name), but I think I've lost it in the last refactor 😱 

You can convert to midi and back to note names, meanwhile...

**Comment by walmik** [comment] 2018-10-18 16:42
Thanks for such a quick response @danigb In the interim, I ll use something on lines of:
```
Tonal.Scale.notes(tonicOctScale).map(el => Tonal.Note.fromMidi(Tonal.Note.midi(el)))
```

**Comment by danigb** [comment] 2018-10-19 16:14
I found the function. I don't know why is not in the API documentation (I will keep this open until I found the cause).

The solution is: 

```js
[ 'D#4', 'E#4', 'F##4', 'G#4', 'A#4', 'B#4', 'C##5' ].map(Note.simplify) // => [ 'D#4', 'F4', 'G4', 'G#4', 'A#4', 'C5', 'D5' ]
```

**Comment by walmik** [comment] 2018-10-19 19:35
Thanks @danigb I ll switch to this in my code for now.

**Comment by danigb** [comment] 2018-10-21 16:55
The documentation is here: http://danigb.github.io/tonal/api/module-Note.html#.simplify 

It doesn't appear on the left bar... 🤔 http://danigb.github.io/tonal/api/

Closing the issue for now...

**Closed by danigb** 2018-10-21 16:55 UTC
